"""Add threat_detected column to connections table

Revision ID: e1a08b67ecbc
Revises: 
Create Date: 2026-03-24 14:04:47.578260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1a08b67ecbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('admin_audit', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('admin_audit', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('admin_audit', 'admin_username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('admin_audit', 'action_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('attack_paths', 'entry_point',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('attack_paths', 'target',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('attack_paths', 'path_hops',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('attack_paths', 'total_risk_score',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=False)
    op.alter_column('attack_paths', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('attack_paths', 'vulnerable_ports_in_path',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('attack_paths', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('config_uploads', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('config_uploads', 'upload_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('config_uploads', 'file_size',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('config_uploads', 'ingestion_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('config_uploads', 'progress_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('config_uploads', 'configs_processed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('config_uploads', 'errors_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('config_uploads', 'warnings_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('config_uploads', 'unsupported_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('config_uploads', 'error_messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('connections', sa.Column('threat_detected', sa.Boolean(), nullable=False))
    op.alter_column('connections', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('connections', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('connections', 'src_ip',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('connections', 'dst_ip',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('connections', 'src_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('connections', 'dst_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('connections', 'protocol',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('connections', 'bytes_sent',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('connections', 'bytes_received',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('connections', 'packets_sent',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('connections', 'packets_received',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('connections', 'action',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('firewall_rules', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('firewall_rules', 'source_ip',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('firewall_rules', 'dest_ip',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('firewall_rules', 'protocol',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('firewall_rules', 'action',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('firewall_rules', 'hit_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('firewall_rules', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('firewall_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('network_topology', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('network_topology', 'device_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('network_topology', 'ports_open',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('network_topology', 'connected_to',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('network_topology', 'is_entry_point',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('network_topology', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('rule_risk_analysis', 'risk_score',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=False)
    op.alter_column('rule_risk_analysis', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('rule_risk_analysis', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('system_health', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('system_health', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('system_health', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('system_health', 'cpu_usage_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('system_health', 'memory_usage_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('system_health', 'active_sessions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('system_health', 'errors_in',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('system_health', 'errors_out',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('threats', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('threats', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('threats', 'src_ip',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('threats', 'dst_ip',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('threats', 'threat_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('threats', 'threat_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('threats', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threats', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('threats', 'threat_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('threats', 'threat_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('threats', 'dst_ip',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('threats', 'src_ip',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('threats', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('threats', 'id',
               existing_type=sa.String(length=36),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('system_health', 'errors_out',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('system_health', 'errors_in',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('system_health', 'active_sessions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('system_health', 'memory_usage_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('system_health', 'cpu_usage_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('system_health', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('system_health', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('system_health', 'id',
               existing_type=sa.String(length=36),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('rule_risk_analysis', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('rule_risk_analysis', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('rule_risk_analysis', 'risk_score',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=True)
    op.alter_column('network_topology', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('network_topology', 'is_entry_point',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('network_topology', 'connected_to',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('network_topology', 'ports_open',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('network_topology', 'device_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('network_topology', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('firewall_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('firewall_rules', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('firewall_rules', 'hit_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('firewall_rules', 'action',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('firewall_rules', 'protocol',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('firewall_rules', 'dest_ip',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('firewall_rules', 'source_ip',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('firewall_rules', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('connections', 'action',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('connections', 'packets_received',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('connections', 'packets_sent',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('connections', 'bytes_received',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('connections', 'bytes_sent',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('connections', 'protocol',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('connections', 'dst_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('connections', 'src_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('connections', 'dst_ip',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('connections', 'src_ip',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('connections', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('connections', 'id',
               existing_type=sa.String(length=36),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('connections', 'threat_detected')
    op.alter_column('config_uploads', 'error_messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('config_uploads', 'unsupported_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('config_uploads', 'warnings_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('config_uploads', 'errors_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('config_uploads', 'configs_processed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('config_uploads', 'progress_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('config_uploads', 'ingestion_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('config_uploads', 'file_size',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('config_uploads', 'upload_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('config_uploads', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('attack_paths', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('attack_paths', 'vulnerable_ports_in_path',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('attack_paths', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('attack_paths', 'total_risk_score',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=True)
    op.alter_column('attack_paths', 'path_hops',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('attack_paths', 'target',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('attack_paths', 'entry_point',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('admin_audit', 'action_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('admin_audit', 'admin_username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('admin_audit', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('admin_audit', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('admin_audit', 'id',
               existing_type=sa.String(length=36),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
